spring:
  application:
    name: library-notification-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: library-notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true
      auto-commit-interval-ms: 1000

server:
  port: 8091

logging:
  level:
    com.yourpackage.notification: INFO
    org.springframework.kafka: DEBUG
